global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  -   job_name: 'common-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['localhost:8080']    # we dockerize our service then remove localhost then including docker file name



  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']


  - job_name: 'inventory-service'
    metrics_path: '/inventory-service/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']


  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']



  - job_name: 'product-service'
    metrics_path: '/product-service/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']
