global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  -   job_name: 'common-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['common-service:8080']    # we dockerize our service then remove localhost then including docker file name



  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']


  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8081']


  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8084']



  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8085']
